---
- hosts: bastion
  roles:
    - role: bastion/openssh/configure
      delegate_to: localhost
      become: false
      tags: [bastion]

- hosts: all
  pre_tasks:
    - set_fact:
        k8s_distro: >-
          {{ k8s_distro | d('k3s') }}

    - set_fact:
        k3s_release: >-
          {{ k3s_release | d('1.23.7') }}
        k3s_version: >-
          {{ k3s_version | d('v1.23.7%2Bk3s1') }}

    - set_fact:
        rke2_release: >-
          {{ rke2_release | d('1.23.7') }}
        rke2_version: >-
          {{ rke2_version | d('v1.23.7%2Brke2r2') }}
        kubectl_version: >-
          {{ kubectl_version | d('1.23.7') }}

- hosts: master:compute
  strategy: linear
  roles:
    - role: python3/package/install

- hosts: master:compute
  gather_facts: true
  gather_subset: [network]
  roles:
    - role: packages/install
    - role: network/gather
    - role: haproxy/service/install
    - role: haproxy/service/configure
  post_tasks:
    - meta: flush_handlers

- hosts: master
  tasks:
    - name: "master/{{ k8s_distro }}/install"
      include_role: { name: "master/{{ k8s_distro }}/install" }

- hosts: master[0]
  tasks:
    - name: "master/{{ k8s_distro }}/bootstrap"
      include_role: { name: "master/{{ k8s_distro }}/bootstrap" }

- hosts: master[1:]
  serial: 1
  tasks:
    - name: "master/{{ k8s_distro }}/replicate"
      include_role: { name: "master/{{ k8s_distro }}/replicate" }

- hosts: compute
  tasks:
    - name: "compute/{{ k8s_distro }}/install"
      include_role: { name: "compute/{{ k8s_distro }}/install" }
    - name: "compute/{{ k8s_distro }}/bootstrap"
      include_role: { name: "compute/{{ k8s_distro }}/bootstrap" }

- hosts: master[0]
  roles:
    - role: master/kubeconfig/fetch
      tags: [kubeconfig]
