---
- name: stat Traefik helm chart tarball
  stat:
    path: &traefik_tgz "/var/tmp/traefik-{{ traefik_chart_version }}.tgz"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: stat_traefik_tgz

- name: download Traefik helm chart (directly)
  get_url:
    url: "https://helm.traefik.io/traefik/traefik-{{ traefik_chart_version }}.tgz"
    dest: *traefik_tgz
    mode: u=rw,go=
  when: not stat_traefik_tgz.stat.exists

- name: slurp Traefik helm chart
  slurp:
    path: *traefik_tgz
  register: slurp_traefik_tgz

- name: create Traefik HelmChart CRD object
  copy:
    dest: "/var/lib/rancher/{{ k8s_distro }}/server/manifests/kub3lo-traefik.yaml"
    mode: u=rw,go=r
    content: |
      ---
      {{ _namespace | to_nice_yaml(indent=2) }}
      ---
      {{ _helmchart | to_nice_yaml(indent=2) }}
  vars:
    _namespace:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: traefik-system
    _helmchart:
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: kub3lo-traefik
        namespace: kube-system
      spec:
        targetNamespace: traefik-system
        chartContent: >-
          {{ slurp_traefik_tgz.content }}
        valuesContent: |
          {% raw %}
          deployment:
            replicas: 2
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: traefik
          {% endraw %}
