---
- ansible.builtin.set_fact:
    backend_servers: >-
      {{ master_hosts | zip(master_ipv4s) | list }}

- name: render haproxy config
  ansible.builtin.template:
    dest: /etc/haproxy/haproxy.cfg
    src: etc/haproxy/haproxy.cfg.j2
    mode: u=rw,go=
  notify:
    - restart haproxy

- name: update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regex: " {{ item }}$"
    line: >-
      127.0.0.1 {{ item }}
  loop: "{{ _hosts[k8s_distro] }}"
  vars:
    _hosts:
      k3s:
        - kub3lo-api
      rke2:
        - kub3lo-disco
        - kub3lo-api
