---
- name: download k3s binary
  get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}%2Bk3s1/k3s"
    dest: "/usr/local/bin/k3s-{{ k3s_version }}"
    mode: u=rwx,go=rx

- name: create k3s symlinks
  file:
    src: "k3s-{{ k3s_version }}"
    dest: "{{ item }}"
    state: link
    mode: u=rwx,go=rx
  loop:
    - /usr/local/bin/k3s
    - /usr/local/bin/kubectl

- import_tasks: "{{ playbook_dir }}/import/registry/setup.yml"

- import_tasks: "{{ playbook_dir }}/import/master/wait/readyz.yml"

- name: read node token
  delegate_to: "{{ groups.master[0] }}"
  run_once: true
  slurp:
    path: /var/lib/rancher/k3s/server/node-token
  register: slurp_token

- name: install kub3lo service
  template:
    src: "{{ item.path }}.j2"
    dest: "/{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - path: etc/conf.d/kub3lo
      mode: u=rw,go=r
    - path: etc/init.d/kub3lo
      mode: u=rwx,go=rx
  vars:
    k3s_node_token: "{{ slurp_token.content | b64decode | trim }}"

- name: enable kub3lo service
  service:
    name: kub3lo
    enabled: true
