---
- name: stat /usr/local/bin/helm
  stat:
    path: /usr/local/bin/helm
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: stat_usr_local_bin_helm

- when: not stat_usr_local_bin_helm.stat.exists
  block:
    - name: download helm binary package
      get_url:
        url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        dest: &helm_tgz "/var/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        mode: u=rw,go=

    - name: extract helm binary package
      unarchive:
        remote_src: true
        src: *helm_tgz
        dest: /usr/local/bin/
        extra_opts:
          - --strip-components=1
          - linux-amd64/helm

    - name: ensure /usr/local/bin/helm is executable
      file:
        path: /usr/local/bin/helm
        mode: u=rwx,go=rx

- name: create ~/.kube/config
  file:
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    src: "{{ item.src | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - dest: ~/.kube/
      state: directory
      mode: u=rwx,go=
    - dest: ~/.kube/config
      state: link
      src: "/etc/rancher/{{ k8s_distro }}/{{ k8s_distro }}.yaml"

- name: ensure stable repo is present
  shell: |
    /usr/local/bin/helm repo add stable \
      https://charts.helm.sh/stable/
  args:
    executable: /bin/bash
  changed_when: false
