---
- name: boostrap python3 intepreter
  script: "{{ playbook_dir }}/roles/python3/package/install/templates/python3.sh"
  args:
    executable: /bin/bash
    creates: /usr/bin/python3
  register: script_python3
  until: script_python3 is success
  retries: 12
  delay: 5

- name: install extra packages
  apk:
    name:
      - bash
      - gawk
      - tar
    state: present
  register: apk_extra
  until: apk_extra is success
  retries: 12
  delay: 5
