---
- name: setup docker.io mirror
  when: registry is defined
  block:
    - name: "create /etc/rancher/{{ k8s_distro }}/"
      ansible.builtin.file:
        path: "/etc/rancher/{{ k8s_distro }}/"
        state: directory
        mode: u=rwx,g=rx,o=

    - name: deploy registries.yaml
      ansible.builtin.copy:
        dest: "/etc/rancher/{{ k8s_distro }}/registries.yaml"
        mode: u=rw,go=r
        content: |
          mirrors:
            docker.io:
              endpoint: ["{{ registry }}"]
