---
- ansible.builtin.assert:
    that: _bastion_inventory_hostname not in _forbidden_inventory_hostnames
    fail_msg: "bastion must not be a part of the cluster"
  vars:
    _bastion_inventory_hostname: >-
      {{ _bastion[0] }}
    _forbidden_inventory_hostnames: >-
      {{ (_master + _compute) | unique }}
    _bastion: >-
      {{ groups[bastion_group | d('bastion')] }}
    _master: >-
      {{ groups[master_group | d('master')] }}
    _compute: >-
      {{ groups[compute_group | d('compute')] }}

- name: create local .ssh directory tree
  ansible.builtin.file:
    path: "{{ item }}/"
    state: directory
    mode: u+rwx,g=rx,o=
  loop:
    - "{{ inventory_dir }}/.ssh"
    - "{{ inventory_dir }}/.ssh/config.d"

- name: generate bastion ssh main config
  ansible.builtin.template:
    dest: "{{ inventory_dir }}/.ssh/config"
    src: sshconfig.j2
    mode: u=rw,g=r,o=

- name: generate bastion ssh cluster config
  ansible.builtin.template:
    dest: "{{ inventory_dir }}/.ssh/config.d/{{ cluster_name }}"
    src: config.d/sshconfig.j2
    mode: u=rw,g=r,o=
