---
- import_tasks: "{{ playbook_dir }}/import/master/wait/readyz.yml"

# sets the "node_token" fact
- import_tasks: "{{ playbook_dir }}/import/master/slurp/token.yml"

- name: configure rke2-server service
  template:
    src: etc/rancher/rke2/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: u=rw,go=
  vars:
    rke2_node_token: "{{ node_token }}"

- name: start rke2-server service
  service:
    name: rke2-server
    state: started
    enabled: true
