---
- ansible.builtin.import_role: { name: master/wait }

# set the "node_token" fact
- ansible.builtin.import_role: { name: master/token }

- name: configure rke2-server service
  ansible.builtin.template:
    src: etc/rancher/rke2/config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: u=rw,go=
  vars:
    rke2_node_token: "{{ node_token }}"

- name: start rke2-server service
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true
