---
- hosts: "{{ bastion_group | d('bastion') }}"
  roles:
    - role: bastion/configure
      delegate_to: localhost
      become: false
      tags: [bastion]

- hosts: "{{ master_group | d('master') }}:{{ compute_group | d('compute') }}"
  strategy: linear
  roles:
    - role: python3/install


- hosts: "{{ master_group | d('master') }}:{{ compute_group | d('compute') }}"
  gather_facts: true
  gather_subset: [network]
  roles:
    - role: packages/install
    - role: network/gather
    - role: haproxy/install
    - role: haproxy/configure
  post_tasks:
    - ansible.builtin.meta: flush_handlers


- hosts: "{{ master_group | d('master') }}"
  tasks:
    - name: master/{{ k8s_distro }}/install
      ansible.builtin.include_role:
        name: master/{{ k8s_distro }}/install

- hosts: "{{ master_group | d('master') }}[0]"
  tasks:
    - name: master/{{ k8s_distro }}/bootstrap
      ansible.builtin.include_role:
        name: master/{{ k8s_distro }}/bootstrap

- hosts: "{{ master_group | d('master') }}[1:]"
  serial: 1
  tasks:
    - name: master/{{ k8s_distro }}/replicate
      ansible.builtin.include_role:
        name: master/{{ k8s_distro }}/replicate


- hosts: "{{ compute_group | d('compute') }}"
  tasks:
    - name: compute/{{ k8s_distro }}/install
      ansible.builtin.include_role:
        name: compute/{{ k8s_distro }}/install

    - name: compute/{{ k8s_distro }}/bootstrap
      ansible.builtin.include_role:
        name: compute/{{ k8s_distro }}/bootstrap


- hosts: "{{ master_group | d('master') }}"
  roles:
    - role: addons/metallb/deploy
      tags: [addons]
    - role: addons/traefik/deploy
      tags: [addons]

    - role: master/kubeconfig/install
    - role: master/kubeconfig/fetch
      run_once: true
      tags: [kubeconfig]
