---
- name: download k3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "/usr/local/bin/k3s-{{ k3s_release }}"
    mode: u=rwx,go=rx

- name: create k3s symlinks
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
    mode: u=rwx,go=rx
  loop:
    - dest: /usr/local/bin/k3s
      src: "k3s-{{ k3s_release }}"
    - dest: /usr/local/bin/kubectl
      src: k3s

- ansible.builtin.import_role:
    name: registry/setup

- name: install kub3lo service
  ansible.builtin.template:
    src: etc/init.d/kub3lo.j2
    dest: /etc/init.d/kub3lo
    mode: u=rwx,go=rx

- name: enable kub3lo service
  ansible.builtin.service:
    name: kub3lo
    enabled: true
