---
- name: download k3s binary
  get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "/usr/local/bin/k3s-{{ k3s_release }}"
    mode: u=rwx,go=rx

- name: create k3s symlinks
  file:
    src: "k3s-{{ k3s_release }}"
    dest: "{{ item }}"
    state: link
    mode: u=rwx,go=rx
  loop:
    - /usr/local/bin/k3s
    - /usr/local/bin/kubectl

- import_tasks: "{{ playbook_dir }}/import/registry/setup.yml"

- name: install kub3lo service
  template:
    src: etc/init.d/kub3lo.j2
    dest: /etc/init.d/kub3lo
    mode: u=rwx,go=rx

- name: enable kub3lo service
  service:
    name: kub3lo
    enabled: true
